version: '3'

services:
  ##########################
  ### SETUP SERVER CONTAINER
  ##########################
  server:
    build: 
     context: .
     dockerfile: ./server/Dockerfile
    network_mode: host
    env_file: .env
    restart: always
    volumes:
      - ./server/logs:/Social-Network-Profiles-Server/logs
    environment:
      - PORT=${APP_PORT}
      - NODE_ENV=${APP_NODE_ENV}
    ports: 
      - ${APP_PORT}:${APP_PORT}

    
  client:
  ##########################
  ### SETUP CLIENT CONTAINER
  ##########################
    build:
      context: .
      dockerfile: ./client/Dockerfile
    env_file: .env
    ports:
      - 3000:80
    volumes:
      - ./client/src/img:/Social-Network-Profiles-Client/src/img
    links:
      - server
    restart: always
